version: '3.3'

services:
    mealplan:
        build:
            context: .
            dockerfile: Dockerfile
        image: mealplan:v1.0
        hostname: mealplan
        container_name: mealplan
        restart: always
        networks:
            - services_net
        ports:
            - 8081:8080

networks:
  services_net:
